### ISSUE TITLE
When typing in filter text fields, cursor jumps to the end after each keystroke

### ISSUE THREAD

**Issue by roryokane** [anton-z-s/linext#1]
## How to reproduce

Start with [this search][example-start] that filters the “Screen size” column on `(5.1,(5.2,(5.3`. I want to add `(5.0,` to the beginning of that filter so I am filtering on `(5.0,(5.1,(5.2,(5.3`.

I move my cursor to the beginning of the “Screen size” filter text field and try to type `(5.0,`. But after typing the `(`, the cursor jumped to the end of the text field, so the field now contains `((5.1,(5.2,(5.35.0,`.

To fix my filter after encountering this bug, I have to cut the misplaced `5.0,`, move the cursor to after the first `(`, and paste, which can get tedious.

## Workaround

As a workaround, I have figured out that I can select all text in the filter text field, copy it, paste it elsewhere to edit it, and paste my edited filter in one go. Of course, this is not the ideal experience.

## Cause of the bug

I suspect that React is recreating the `input` element from scratch after each rerender. Additional evidence for this is that I can’t use my browser’s Undo function after changing the text field.

I would have assumed that you forgot to give the filter text field a `key`, but you do give it one:

https://github.com/anton-z-s/linext/blob/7acddc0b6ebc6b0d95f69d4401009e04d8073e98/src/components/DevicesTable.js#L713-L723

[example-start]: https://anton-z-s.github.io/linext/#/?columns=vendor|name|cameras|screen|screen_res|ram|release&sorted=release_desc&filtered=W3siaWQiOiJtYWludGFpbmVkIiwidmFsdWUiOlsiWWVzIl19LHsiaWQiOiJ2ZW5kb3IiLCJ2YWx1ZSI6W119LHsiaWQiOiJjcHUiLCJ2YWx1ZSI6W119LHsiaWQiOiJzb2MiLCJ2YWx1ZSI6W119LHsiaWQiOiJjcHVfY29yZXMiLCJ2YWx1ZSI6W119LHsiaWQiOiJncHUiLCJ2YWx1ZSI6W119LHsiaWQiOiJjdXJyZW50X2JyYW5jaCIsInZhbHVlIjpbXX0seyJpZCI6InR5cGUiLCJ2YWx1ZSI6W119LHsiaWQiOiJyZWxlYXNlIiwidmFsdWUiOltdfSx7ImlkIjoiYmF0dGVyeV90ZWNoIiwidmFsdWUiOltdfSx7ImlkIjoiYXJjaGl0ZWN0dXJlIiwidmFsdWUiOltdfSx7ImlkIjoic2NyZWVuIiwidmFsdWUiOiIoNS4xLCg1LjIsKDUuMyJ9XQ==

**Comment by anton-z-s** [comment]
fixed in #2

**Comment by roryokane** [comment]
Thanks. For practical purposes this is fixed. But note that I can still reproduce the bug if I mash on the keyboard to type very quickly.

The reason the bug can still happen after the fix is probably that the fix sets the cursor position after `requestAnimationFrame`. Maybe what’s happening is that if I type a character during the next animation frame, the cursor position of my typed character overrides the cursor position set in the `requestAnimationFrame` callback.

I think the ideal fix would be to prevent the `input` element from being recreated from scratch, as I suggested. This would fix Undo not working in that text field, a bug which is still present.

I still don’t know how to go about that fix, though. The only way I know to fix such problems is by giving the element the same `key` attribute before and after the change, but it looks like that code already does that.

**Comment by anton-z-s** [comment]
It's a bug in react-table, it's being reported in their repo, but a fix isn't that straightforward.

This project uses react-table v6, whereas v7 is available. I can confirm the bug isn't reproducible in v7. But update would require a major rewrite as react-table v7 is vastly different from v6. 
I might do that in the future.
